import '@/styles/globals.css'
import type { Metadata } from 'next'
import { poppins } from '@/styles/fonts'
import GeneratorNavbar from '@/components/GeneratorNavbar'

export const metadata: Metadata = {
  title: {
    default: 'Readme Generator  ',
    template: 'Readme Generator | %s '
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-[#0A0A0A] min-h-screen min-w-screen ${poppins.className} text-secondary`}>
        <GeneratorNavbar />
        {children}</body>
    </html>
  )
}
